name: Deploy

on:
  workflow_call:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Clone the code
        uses: actions/checkout@v7

      - name: Deploy via NGINX
        run: cp index.html /var/www/html

      - name: Deploy
        run: echo "Deploying..."
